service: linetest # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  profile: ${opt:profile}
  stage: dev
  region: ap-northeast-1
  usagePlan:
    throttle:
      burstLimit: 1000
      rateLimit: 1000
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**
custom:
  defaultStage: dev
  defaultProfile: default
  defaultRegion: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: get_account
          method: post
          cors: true
